lab8/src/Frontend/Models/ErrorViewModel.cs
using System;

namespace Frontend.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

lab8/src/Frontend/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Frontend.Models;
using System.Net.Http;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using Frontend.Types;

namespace Frontend.Controllers
{
    public class HomeController : Controller
    {
        private const string UriBackendAddress = "http://localhost:5000/";
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Upload(string data, RegionType region)
        {
            Data uploadedData = new Data { TextId = data, Region = region };
            string id = null;
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            client.BaseAddress = new Uri(UriBackendAddress);
            HttpResponseMessage response = await client.PostAsJsonAsync($"api/values", uploadedData);
            id = await response.Content.ReadAsStringAsync();

            return RedirectToAction("TextDetails", new { textId = id });
        }

        [HttpGet("TextDetails")]
        public async Task<IActionResult> TextDetails(string textId)
        {
            Console.WriteLine(textId);
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(UriBackendAddress);
            HttpResponseMessage response = await client.PostAsJsonAsync($"/api/values/rank", textId.Split("\"")[1]);
            string rank = await response.Content.ReadAsStringAsync();
            if (rank != "")
            {
                return View(new RankData {TextId = textId, Rank = rank});
            }

            return View(null);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lab8/src/Frontend/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Frontend.Models;
using System.Net.Http;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using Frontend.Types;
using System.Net.Sockets;

namespace Frontend.Controllers
{
    [Route("[controller]")]
    public class StatisticsController : Controller
    {
        private const string UriBackendAddress = "http://localhost:5000/";

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(UriBackendAddress);
            StatisticsData result = null;
            HttpResponseMessage httpResponse = null;
            Console.WriteLine($"HttpResponseMessage");
            httpResponse = await client.GetAsync("/api/values/statistic");
            if (httpResponse.IsSuccessStatusCode)
            {
                result = await httpResponse.Content.ReadAsAsync<StatisticsData>(); 
                Console.WriteLine($"TextNum: {result.TextNum} High: {result.HighRankPart} Avg: {result.AvgRank} NotProccessed: {result.NotProccessed}");
            }

            return View(result);
        }
    }
}

lab8/src/Frontend/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

lab8/src/Frontend/Views/Home/TextDetails.cshtml
@{
    ViewData["Title"] = "Text Details";
    @model RankData;
}
<div class="row body-content">
    @if(Model != null)
    {
        <div>
            <p>Text id: @Model.TextId</p>
            <br />
            <p>Rank: @Model.Rank</p>
        </div>
    }
    else
    {
        <p>"You limit is over"</p>
    }
</div>

lab8/src/Frontend/Views/Home/Upload.cshtml
@{
    ViewData["Title"] = "Data input";
}
<div>
    <h2>Форма ввода</h2>
    <form method="post">
        Data: <input name="data" type="text"/><br>
        <p><select name="region">
            <option value=@RegionType.Ru>RUS</option>
            <option value=@RegionType.Eu>EU</option>
            <option value=@RegionType.Usa>USA</option>
        </select></p>
        <input type="submit">
    </form>
</div>

lab8/src/Frontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Frontend</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Frontend</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Statistics" asp-action="Index">Statistics</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Upload">Upload</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Protasov Ilya lab 5 PS-31 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

lab8/src/Frontend/Views/Statistics/Index.cshtml
@{
    ViewData["Title"] = "Statistics";
    @model StatisticsData;
}
<div class="row body-content">
    @if(Model != null)
    {
        <div>
            <p>Text number: @Model.TextNum</p>
            <br />
            <p>High rank part: @Model.HighRankPart</p>
            <br />
            <p>Average rank: @Math.Round(Model.AvgRank, 2)</p>
            <br />
            <p>NotProccessed: @Model.NotProccessed</p>
        </div>
    }
    else
    {
        <p>No statisitcs info</p>
    }
</div>